spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websocket
    username: root
    password: 10061
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
        ddl-auto: none  # DB 스키마 자동 업데이트 (운영에서는 validate나 none 추천)
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 기준
            format_sql: true  # SQL 예쁘게 출력
        show-sql: true  # SQL 실행 로그 출력


jwt:
  issuer: s23068@gmail.com
  secretKey: study-springboot-is-a-secure-key-32-characters

server:
  port: 8089

